name: Publish

permissions:
  id-token: write
  attestations: write

# on: push
on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ] #todo

jobs:
  build:
    name: Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18.6.0

      - name: Build project
        run: |
          yarn install --immutable && \
          yarn build

      - name: Upload build artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: bundles/@yarnpkg/*
          name: artifact.zip

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: artifact.zip
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
